name: Python CI

# このワークフローが実行されるトリガー
on:
  pull_request:
    branches:
      - main  # PRの対象ブランチを指定

jobs:
  test:
    name: Run Python Tests and Lint
    runs-on: ubuntu-latest  # ジョブが実行される環境

    # 複数のPythonバージョンでテストを実行する例
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    # 1. GitHubリポジトリのコードをチェックアウト
    - name: Check out code
      uses: actions/checkout@v3

    # 2. Python環境をセットアップ
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # 3. 必要な依存関係をインストール
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. コード品質チェック（例: flake8）
    - name: Run Linter (flake8)
      run: |
        pip install flake8
        flake8 .

    # 5. テストの実行（例: pytest）
    - name: Run Tests
      run: |
        pip install pytest
        pytest
